<h1>CUIABÁ VAI SEDIAR MAIOR FESTA DO SETOR DE REPARAÇÃO DO CENTRO-OESTE</h1>

<img class="ilustra" src="noticias/imagens/pitstop1.png" alt="Foto: www.olhardireto.com.br" title="Diretores da FIEMT, Sindirepa e representantes de diversos setores se reúnem para o lançamento da Feira Pit Stop, em Cuiabá." />

<p>A capital mato-grossense terá, pela primeira vez, uma feira que atenderá a cadeia produtiva do setor de reparação e automotivo. Trata-se do PIT STOP - Feira das Indústrias Mecânicas, Retíficas e Acessórios de Mato Grosso, que vai ocorrer de 13 a 15 de novembro, no Centro de Eventos do Pantanal, com entrada gratuita. Agregando empresas e negócios de mais de 25 segmentos diferentes que compõe o setor da reparação, o evento pretende fazer parte do calendário nacional de feiras e se consolidar como o maior da região Centro-Oeste.</p>
<p>Em sua primeira edição, a expectativa é de que o evento receba aproximadamente oito mil visitantes, entre lojistas, representantes, distribuidores, empresários do ramo de mecânica, retífica e acessórios para automóveis e máquinas e equipamentos para a indústria. “A feira é uma solicitação do setor há muitos anos e será um marco para o segmento da reparação”, disse o coordenador da feira, que também é diretor do Sindirepa e do Sistema Federação das Indústrias no Estado de Mato Grosso (Sistema Fiemt), Elias Correia Pedrozo. “Sabemos da responsabilidade por ser a primeira feira, mas o setor se uniu e comprou a ideia”, acrescentou.</p>
<p>A organização do evento espera a participação de mais de 60 expositores, entre empresas de Mato Grosso e de outros Estados brasileiros, totalizando 90 estandes. “Será a grande oportunidade para as empresas do segmento apresentarem seus produtos e serviços e também para Mato Grosso se destacar como Estado com grande potencial para investimentos no setor de reparação e veículos”, avalia o presidente em exercício do Sistema Fiemt, Jandir Milan.</p>
<p>O PIT STOP apresentará as mais recentes novidades para os segmentos de mecânica, retíficas, linha pesada (caminhões), autopeças, óleo, amortecedores, pneus, radiadores, rolamentos, bateria, elevadores, injeção eletrônica, alinhamento, suspensão, combustível, máquinas, concessionárias, revendas, seguradora, som e acessório, pintura e recuperação, auto-elétrica, tornearia, entre outros.</p>
<h2>Atividades paralelas</h2>
<p>Diversas atividades serão desenvolvidas paralelamente à feira, como o II Encontro Mato-grossense da Indústria Metal Mecânica, promovido pelo Serviço Nacional de Aprendizagem Industrial (Senai–MT), e a Inspeção Preventiva Veicular Gratuita, que vai reunir mais de 30 empresas mecânicas e retíficas, com aproximadamente 70 profissionais, para inspecionar gratuitamente os veículos dos visitantes da feira. A meta é atender de 500 a 600 automóveis em dois dias e orientar a população para a importância da manutenção preventiva veicular. </p>

<p class="fonte">Fonte: <a target="correiomecanico" href="http://www.correiomecanico.com.br">Correio Mecânico</a></p>
<p class="veja">Veja também: <a target="correiomecanico" href="http://blog.correiomecanico.com.br/2009/09/28/evento-oportuniza-aprendizada-para-dezenas-de-mecanicos-em-sp/">Evento oportuniza aprendizado para dezenas de mecânicos em SP</a></p>