<h1>CUIABï¿½ VAI SEDIAR MAIOR FESTA DO SETOR DE REPARAï¿½ï¿½O DO CENTRO-OESTE</h1>

<img class="ilustra" src="noticias/imagens/pitstop1.png" alt="Foto: www.olhardireto.com.br" title="Diretores da FIEMT, Sindirepa e representantes de diversos setores se reï¿½nem para o lanï¿½amento da Feira Pit Stop, em Cuiabï¿½." />

<p>A capital mato-grossense terï¿½, pela primeira vez, uma feira que atenderï¿½ a cadeia produtiva do setor de reparaï¿½ï¿½o e automotivo. Trata-se do PIT STOP - Feira das Indï¿½strias Mecï¿½nicas, Retï¿½ficas e Acessï¿½rios de Mato Grosso, que vai ocorrer de 13 a 15 de novembro, no Centro de Eventos do Pantanal, com entrada gratuita. Agregando empresas e negï¿½cios de mais de 25 segmentos diferentes que compï¿½e o setor da reparaï¿½ï¿½o, o evento pretende fazer parte do calendï¿½rio nacional de feiras e se consolidar como o maior da regiï¿½o Centro-Oeste.</p>
<p>Em sua primeira ediï¿½ï¿½o, a expectativa ï¿½ de que o evento receba aproximadamente oito mil visitantes, entre lojistas, representantes, distribuidores, empresï¿½rios do ramo de mecï¿½nica, retï¿½fica e acessï¿½rios para automï¿½veis e mï¿½quinas e equipamentos para a indï¿½stria. ï¿½A feira ï¿½ uma solicitaï¿½ï¿½o do setor hï¿½ muitos anos e serï¿½ um marco para o segmento da reparaï¿½ï¿½oï¿½, disse o coordenador da feira, que tambï¿½m ï¿½ diretor do Sindirepa e do Sistema Federaï¿½ï¿½o das Indï¿½strias no Estado de Mato Grosso (Sistema Fiemt), Elias Correia Pedrozo. ï¿½Sabemos da responsabilidade por ser a primeira feira, mas o setor se uniu e comprou a ideiaï¿½, acrescentou.</p>
<p>A organizaï¿½ï¿½o do evento espera a participaï¿½ï¿½o de mais de 60 expositores, entre empresas de Mato Grosso e de outros Estados brasileiros, totalizando 90 estandes. ï¿½Serï¿½ a grande oportunidade para as empresas do segmento apresentarem seus produtos e Serviços e tambï¿½m para Mato Grosso se destacar como Estado com grande potencial para investimentos no setor de reparaï¿½ï¿½o e Vesãculosï¿½, avalia o presidente em exercï¿½cio do Sistema Fiemt, Jandir Milan.</p>
<p>O PIT STOP apresentarï¿½ as mais recentes novidades para os segmentos de mecï¿½nica, retï¿½ficas, linha pesada (caminhï¿½es), autopeï¿½as, ï¿½leo, amortecedores, pneus, radiadores, rolamentos, bateria, elevadores, injeï¿½ï¿½o eletrï¿½nica, alinhamento, suspensão, Combustsãvel, mï¿½quinas, concessionï¿½rias, revendas, seguradora, som e acessï¿½rio, pintura e recuperaï¿½ï¿½o, auto-elï¿½trica, tornearia, entre outros.</p>
<h2>Atividades paralelas</h2>
<p>Diversas atividades serï¿½o desenvolvidas paralelamente ï¿½ feira, como o II Encontro Mato-grossense da Indï¿½stria Metal Mecï¿½nica, promovido pelo Serviço Nacional de Aprendizagem Industrial (Senaiï¿½MT), e a Inspeï¿½ï¿½o Preventiva Veicular Gratuita, que vai reunir mais de 30 empresas mecï¿½nicas e retï¿½ficas, com aproximadamente 70 profissionais, para inspecionar gratuitamente os Vesãculos dos visitantes da feira. A meta ï¿½ atender de 500 a 600 automï¿½veis em dois dias e orientar a populaï¿½ï¿½o para a importï¿½ncia da manutenï¿½ï¿½o preventiva veicular. </p>

<p class="fonte">Fonte: <a target="correiomecanico" href="http://www.correiomecanico.com.br">Correio Mecï¿½nico</a></p>
<p class="veja">Veja tambï¿½m: <a target="correiomecanico" href="http://blog.correiomecanico.com.br/2009/09/28/evento-oportuniza-aprendizada-para-dezenas-de-mecanicos-em-sp/">Evento oportuniza aprendizado para dezenas de mecï¿½nicos em SP</a></p>