<h1>CUIAB� VAI SEDIAR MAIOR FESTA DO SETOR DE REPARA��O DO CENTRO-OESTE</h1>

<img class="ilustra" src="noticias/imagens/pitstop1.png" alt="Foto: www.olhardireto.com.br" title="Diretores da FIEMT, Sindirepa e representantes de diversos setores se re�nem para o lan�amento da Feira Pit Stop, em Cuiab�." />

<p>A capital mato-grossense ter�, pela primeira vez, uma feira que atender� a cadeia produtiva do setor de repara��o e automotivo. Trata-se do PIT STOP - Feira das Ind�strias Mec�nicas, Ret�ficas e Acess�rios de Mato Grosso, que vai ocorrer de 13 a 15 de novembro, no Centro de Eventos do Pantanal, com entrada gratuita. Agregando empresas e neg�cios de mais de 25 segmentos diferentes que comp�e o setor da repara��o, o evento pretende fazer parte do calend�rio nacional de feiras e se consolidar como o maior da regi�o Centro-Oeste.</p>
<p>Em sua primeira edi��o, a expectativa � de que o evento receba aproximadamente oito mil visitantes, entre lojistas, representantes, distribuidores, empres�rios do ramo de mec�nica, ret�fica e acess�rios para autom�veis e m�quinas e equipamentos para a ind�stria. �A feira � uma solicita��o do setor h� muitos anos e ser� um marco para o segmento da repara��o�, disse o coordenador da feira, que tamb�m � diretor do Sindirepa e do Sistema Federa��o das Ind�strias no Estado de Mato Grosso (Sistema Fiemt), Elias Correia Pedrozo. �Sabemos da responsabilidade por ser a primeira feira, mas o setor se uniu e comprou a ideia�, acrescentou.</p>
<p>A organiza��o do evento espera a participa��o de mais de 60 expositores, entre empresas de Mato Grosso e de outros Estados brasileiros, totalizando 90 estandes. �Ser� a grande oportunidade para as empresas do segmento apresentarem seus produtos e Serviços e tamb�m para Mato Grosso se destacar como Estado com grande potencial para investimentos no setor de repara��o e Veículos�, avalia o presidente em exerc�cio do Sistema Fiemt, Jandir Milan.</p>
<p>O PIT STOP apresentar� as mais recentes novidades para os segmentos de mec�nica, ret�ficas, linha pesada (caminh�es), autope�as, �leo, amortecedores, pneus, radiadores, rolamentos, bateria, elevadores, inje��o eletr�nica, alinhamento, suspensão, Combustível, m�quinas, concession�rias, revendas, seguradora, som e acess�rio, pintura e recupera��o, auto-el�trica, tornearia, entre outros.</p>
<h2>Atividades paralelas</h2>
<p>Diversas atividades ser�o desenvolvidas paralelamente � feira, como o II Encontro Mato-grossense da Ind�stria Metal Mec�nica, promovido pelo Serviço Nacional de Aprendizagem Industrial (Senai�MT), e a Inspe��o Preventiva Veicular Gratuita, que vai reunir mais de 30 empresas mec�nicas e ret�ficas, com aproximadamente 70 profissionais, para inspecionar gratuitamente os Veículos dos visitantes da feira. A meta � atender de 500 a 600 autom�veis em dois dias e orientar a popula��o para a import�ncia da manuten��o preventiva veicular. </p>

<p class="fonte">Fonte: <a target="correiomecanico" href="http://www.correiomecanico.com.br">Correio Mec�nico</a></p>
<p class="veja">Veja tamb�m: <a target="correiomecanico" href="http://blog.correiomecanico.com.br/2009/09/28/evento-oportuniza-aprendizada-para-dezenas-de-mecanicos-em-sp/">Evento oportuniza aprendizado para dezenas de mec�nicos em SP</a></p>